### PR TITLE
Social media links added

### PR DESCRIPTION
**Pull request by unnikrishnan2002**
## Related Issue 

- Information about the related issue

Closes: #177 

### Describe the changes you've made

Social media links are added at the bottom of the file

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation update.
- [ ] This change requires a documentation update

## Checklist

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

 Original           | Updated
 :--------------------: |:--------------------:
 original screenshot | updated screenshot |

## Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/web3community/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by krishguptadev — CHANGES_REQUESTED** [review]
Can't we have shields.io badges on the top instead?

**Comment by unnikrishnan2002** [comment]
> Can't we have shields.io badges on the top instead?

Yeah but in that case all social media handles don't cover right ?

**Comment by krishguptadev** [comment]
> > Can't we have shields.io badges on the top instead?
> 
> Yeah but in that case all social media handles don't cover right ?

See this: https://github.com/alexandresanlim/Badges4-README.md-Profile

**Comment by unnikrishnan2002** [comment]
> > > Can't we have shields.io badges on the top instead?
> > 
> > 
> > Yeah but in that case all social media handles don't cover right ?
> 
> See this: https://github.com/alexandresanlim/Badges4-README.md-Profile

Ohh graphic badges . I thought the other ones on the shields.io website. Sounds good to me should I change then?

**Comment by krishguptadev** [comment]
Yeah! Please change them! Just undraft this PR once done.

**Review by Panquesito7 — APPROVED** [review]
For me, this is looking great! 🚀 This is what we currently use on our `.github` repository, so it looks good. Thanks! 😄👍

**Comment by krishguptadev** [comment]
> For me, this is looking great! 🚀 This is what we currently use on our `.github` repository, so it looks good. Thanks! 😄👍

We discussed about adding badges in the issue :/

**Comment by shuklaritvik06** [comment]
ss

If this looks good to you all,

@unnikrishnan2002 you can use

```

<img src="https://user-images.githubusercontent.com/73097560/115834477-dbab4500-a447-11eb-908a-139a6edaec5c.gif">
<p align="center"><strong>Connect with us</strong></p>
<p align="center">
</a>
<a href="https://www.instagram.com/web3community/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" target="_blank" />
</a>
<a href="https://www.linkedin.com/company/web3community/">
  <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" target="_blank" />  
</a>
<a href="https://dsc.gg/web3community">
   <img src="https://img.shields.io/discord/835424705410236427?logo=discord&style=for-the-badge" target="_blank" />
</a>
<a href="https://twitter.com/web3community">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" target="_blank" />
</a>
<a href="https://github.com/web3community">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" target="_blank" />
</a>
</p>
```

Remove the footer gif and Don't forget to join our discord, replace this :)

**Comment by unnikrishnan2002** [comment]
> ss
> 
> If this looks good to you all,
> 
> @unnikrishnan2002 you can use
> 
> ```
> 
> 
> <p align="center"><strong>Connect with us</strong></p>
> <p align="center">
> </a>
> <a href="https://www.instagram.com/web3community/">
>    
> </a>
> <a href="https://www.linkedin.com/company/web3community/">
>     
> </a>
> <a href="https://dsc.gg/web3community">
>    
> </a>
> <a href="https://twitter.com/web3community">
>    
> </a>
> <a href="https://github.com/web3community">
>    
> </a>
> </p>
> ```
> 
> Remove the footer gif and Don't forget to join our discord, replace this :)

Sure . I will do that

**Review by shuklaritvik06 — APPROVED** [review]
LGTM thanks :)

**Review by vinzvinci — COMMENTED** [review]
LGTM :+1:

**Review by KukretiShubham — COMMENTED** [review]
LGTM

**Pull request merged**
