### PR TITLE
chore: Center all the headers

### PR DESCRIPTION
**Pull request by Panquesito7**
### Describe the changes you've made

- Center all the headers in the `README.md` file.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update.
- [ ] This change requires a documentation update

## How Has This Been Tested?

I don't think this applies here.

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots (if applicable)

 Original           | Updated
 :--------------------: |:--------------------:
image | image |
 
## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/web3community/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by krishguptadev — CHANGES_REQUESTED** [review]
Totally looks weird when the content is not on center. UX#Readibility#Alignment

**Comment by Panquesito7** [comment]
> Totally looks weird when the content is not on center. UX#Readibility#Alignment

Let's see what the other maintainers think. 🙂

**Comment by shuklaritvik06** [comment]
It looks weird 😅

**Review by vinzvinci — COMMENTED** [review]
Can't agree with this

**Comment by shuklaritvik06** [comment]
So As All maintainers think this change is not good to have so I am closing this PR

**Comment by KukretiShubham** [comment]
Header at the center looks fine to me. I don't know why 🤔

**Comment by krishguptadev** [comment]
> Header at the center looks fine to me. I don't know why 🤔

Doesn't look any good to me, @vinzvinci and @shuklaritvik06 though. I've also added the reason it doesn't look good in my first comment (UX#Readibility#Alignment)

**Pull request closed without merging**
